openapi: 3.0.0
servers:
  - url: 'https://localhost:5000/'
    description: Nodejs server
info:
  title: External process communication
  description: Specification of communication between external process and CobiGen
  version: 1.0.0
  x-rootpackage: com.devonfw.poc
paths:
  /processmanagement/inputReader/isValidInput/:
    post:
      description: Returns true or false whether it is a valid input for generation
      requestBody:
        $ref: '#/components/requestBodies/InputFile'
      operationId: isValidInput
      responses:
        '200':
          description: Returns true or false whether it is a valid input for generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValidInput:
                    type: boolean
        '404':
          description: Not found
  /processmanagement/inputReader/getInputModel/:
    post:
      description: Requesting map model of the input file
      requestBody:
        $ref: '#/components/requestBodies/InputFile'
      operationId: getInputObjects
      responses:
        '200':
          description: Returns a model in JSON format
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Model'
        '404':
          description: Not found
  /processmanagement/merger/merge/:
    post:
      description:  Merges two files and returns the result
      requestBody:
        $ref: '#/components/requestBodies/Merger'
      operationId: merge
      responses:
        '200':
          description: Returns resolved variables
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Not found
components:
    schemas:
        Models:
          x-component: processmanagement
          description: Array of models
          type: array
          items:
            type: object
            properties:
              Field:
                $ref: '#/components/schemas/Model'
        Model:
          x-component: processmanagement
          description: Data model of the input file
          type: object
          properties:
            fileType:
              type: string
              maxLength: 30
              minLength: 1
              uniqueItems: true
            fileName:
              type: string
              maxLength: 30
              minLength: 1
              uniqueItems: true
            Fields:
              $ref: '#/components/schemas/Fields'
            Imports: 
              $ref: '#/components/schemas/Imports'
        Fields:
          x-component: processmanagement
          description: Array of fields
          type: array
          items:
            type: object
            properties:
              Field:
                $ref: '#/components/schemas/Field'
        Field:
          x-component: processmanagement
          description: Field
          type: object
          properties:
            fieldName:
                type: string
            fieldType:
                type: string
        Imports:
          x-component: processmanagement
          description: Array of imports
          type: array
          items:
            type: object
            properties:
              Import:
                $ref: '#/components/schemas/Import'
        Import:
          x-component: processmanagement
          description: Field
          type: object
          properties:
            importValue:
                type: string
        InputFile:
          x-component: processmanagement
          description: Input file
          type: object
          properties:
            contents:
              type: string
        Merger:
          x-component: processmanagement
          description: Merger properties
          type: object
          properties:
            baseContent:
              type: string
            patchContent:
              type: string
            patchOverrides:
              type: boolean


    requestBodies:
        Model:
          description: Data model of the file in JSON format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          required: true
        Models:
          description: Array of models (JSON format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Models'
          required: true
        InputFile:
          description: Input file path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InputFile'
          required: true
        Merger:
          description: Objects to be merged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merger'
          required: true
 